name: mob_se
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  characters: ^1.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_contact_picker: ^0.0.6
  flutter_phone_direct_caller: ^2.1.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  # dependance pour base de donnees local isar
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
