name: mob_se
description: "A new Flutter project."
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  characters: ^1.3.0
  contacts_service: ^0.6.3
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_contact_picker: ^0.0.6
  flutter_phone_direct_caller: ^2.1.1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  info_popup: ^4.3.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  line_icons: ^2.0.3
  lottie: ^3.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  vibration: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          #   #uses-material-design: true
